language: android
jdk: oraclejdk7

android:
    components:
        - android-21
        - build-tools-21.0.0
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5

before_install:
    - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin; fi
    - chmod a+x ndk.bin
    - ./ndk.bin -y | grep -v Extracting
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10d
    - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
    - make
